import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/nav/NavBar";
import { Footer } from "@/components/general/Footer";
import { ToastProvider } from "@/providers/ToastContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SLE Developers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
          <NavBar />
          <span className="already-loaded"></span>
          {children}
          <Footer />
        </ToastProvider>
      </body>
    </html>
  );
}
